version: '3.5'

services:
  postgres:
    container_name: postgres_container_native
    image: postgres
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pwd
      PGDATA: /data/postgres
      POSTGRES_DB: meas
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres-native
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container_native
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5051:80"
    networks:
      - postgres-native
    restart: unless-stopped

  measurements:
    container_name: measurements_container_native
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.native
    ports:
      - "8081:8080"
    networks:
      - postgres-native
    depends_on:
      - postgres
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/meas
      QUARKUS_DATASOURCE_USERNAME: postgres_user
      QUARKUS_DATASOURCE_PASSWORD: postgres_pwd
    volumes:
      - measurements:/deployments
    restart: unless-stopped

networks:
  postgres-native:
    name: postgres-native-network
    driver: bridge

volumes:
  postgres:
  pgadmin:
  measurements:
